name: Build and release workflow

on:
  push:
    tags:
      - "*" # triggers only if push new tag version, like `0.8.4` or else

jobs:
  build:
    name: GoReleaser build
    runs-on: ubuntu-latest

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # See: https://goreleaser.com/ci/actions/

      - name: Setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
        id: go

      - name: Generate sbom
        run: |
          wget -qO- "https://github.com/spdx/spdx-sbom-generator/releases/download/v0.0.13/spdx-sbom-generator-v0.0.13-linux-amd64.tar.gz" | \
          tar xvz && \
          chmod +x spdx-sbom-generator
          ./spdx-sbom-generator --path .
          rm spdx-sbom-generator
        shell: bash

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2.7.0
        with:
          version: latest
          args: release --config ./.goreleaser.yml --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GO_RELEASER_GITHUB_TOKEN }}
